require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require 'json'

podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, '15.1'

install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'fullcircle' do
  use_frameworks! :linkage => :static

  config = use_native_modules!
  use_expo_modules!(modules_provider: config[:modulesProvider])

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'].nil? || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )
    
    # Set deployment target to 15.1 for everything
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Fix BoringSSL-GRPC compilation error
        if target.name.include?('BoringSSL-GRPC')
          if config.build_settings['OTHER_CFLAGS']
            other_cflags = config.build_settings['OTHER_CFLAGS']
            if other_cflags.is_a?(String)
              config.build_settings['OTHER_CFLAGS'] = other_cflags.split(' ').reject { |flag| flag == '-G' }.join(' ')
            elsif other_cflags.is_a?(Array)
              config.build_settings['OTHER_CFLAGS'] = other_cflags.reject { |flag| flag == '-G' }
            end
          end
          
          if config.build_settings['OTHER_CPLUSPLUSFLAGS']
            other_cplusplusflags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
            if other_cplusplusflags.is_a?(String)
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] = other_cplusplusflags.split(' ').reject { |flag| flag == '-G' }.join(' ')
            elsif other_cplusplusflags.is_a?(Array)
              config.build_settings['OTHER_CPLUSPLUSFLAGS'] = other_cplusplusflags.reject { |flag| flag == '-G' }
            end
          end
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end